In [1]:
import numpy as np
import torch

In [2]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [4]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [5]:
t = torch.FloatTensor([
                       [1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
])
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [6]:
print(t.dim())
print(t.size())
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([3, 3])
tensor([2., 5., 8.])
torch.Size([3])
tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])


In [7]:
t.size()[1]

3

In [8]:
print(t.shape)

torch.Size([3, 3])


In [9]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [11]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])


In [12]:
print(t.mean(axis=0))
print(t.mean(axis=1))

tensor([2., 3.])
tensor([1.5000, 3.5000])


In [13]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [14]:
print(t.max())

tensor(4.)


In [16]:
ret = t.max(dim=0)

In [20]:
ret

torch.return_types.max(values=tensor([3., 4.]), indices=tensor([1, 1]))

In [23]:
ret.values, ret.indices

(tensor([3., 4.]), tensor([1, 1]))

In [24]:
x = torch.FloatTensor([[1,2], [3, 4]])
y = torch.FloatTensor([[5,6], [7,8]])
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [25]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
