In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
torch.manual_seed(1)

# Training Data

In [8]:
x_data = [[1, 2], [2, 3], [3, 1], [4,3], [5,3], [6,2]]
y_data = [0,0,0,1,1,1]

In [9]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data).view(-1, 1)

In [10]:
x_train.shape, y_train.shape

(torch.Size([6, 2]), torch.Size([6, 1]))

# Computing the hypothesis

In [13]:
W = torch.randn((2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [14]:
W, b

(tensor([[0.6614],
         [0.2669]], requires_grad=True), tensor([0.], requires_grad=True))

In [18]:
hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W)+b))) # replaceable with torch.sigmoid() function

In [16]:
print(hypothesis)
print(hypothesis.shape)

tensor([[0.7677],
        [0.8932],
        [0.9047],
        [0.9691],
        [0.9838],
        [0.9890]], grad_fn=<MulBackward0>)
torch.Size([6, 1])


# Computing the Cost Function

In [19]:
losses = -(y_train * torch.log(hypothesis)\
           + (1 - y_train) * torch.log(1 - hypothesis))
print(losses)

tensor([[1.4596],
        [2.2365],
        [2.3511],
        [0.0314],
        [0.0163],
        [0.0110]], grad_fn=<NegBackward0>)


In [20]:
cost = losses.mean()
print(cost)

tensor(1.0176, grad_fn=<MeanBackward0>)


In [23]:
# upper code is replaceable with
# torch.nn.functional.binary_cross_entropy(hypothesis, y_train)

# Whole Training Procedure

In [25]:
W = torch.randn((2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=0.1)
epochs = 1000
for epoch in range(epochs):
  hypothesis = torch.sigmoid(x_train.matmul(W) + b)
  cost = F.binary_cross_entropy(hypothesis, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print("Epoch {:4d}/{} Cost {:.6f}".format(epoch, epochs, cost.item()))

Epoch    0/1000 Cost 1.517360
Epoch  100/1000 Cost 0.420388
Epoch  200/1000 Cost 0.353903
Epoch  300/1000 Cost 0.304714
Epoch  400/1000 Cost 0.266224
Epoch  500/1000 Cost 0.235672
Epoch  600/1000 Cost 0.211063
Epoch  700/1000 Cost 0.190938
Epoch  800/1000 Cost 0.174241
Epoch  900/1000 Cost 0.160201


# Evaluation

In [29]:
 y_test = torch.Tensor([0,0,0,1,1])
 hypothesis = torch.FloatTensor([0.1, 0.3, 0.5, 0.7, 0.9])
 prediction = (hypothesis >= torch.FloatTensor([0.5])).int()
 print(prediction)

tensor([0, 0, 1, 1, 1], dtype=torch.int32)


In [31]:
print(y_test)
print(prediction)

tensor([0., 0., 0., 1., 1.])
tensor([0, 0, 1, 1, 1], dtype=torch.int32)


In [32]:
correct = y_test.int() == prediction.int()

In [35]:
correct.sum().item()

4

# Higher Implementation with Class

In [51]:
x_data = [[1, 2], [2, 3], [3, 1], [4,3], [5,3], [6,2]]
y_data = [0,0,0,1,1,1]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data).view(-1, 1)

In [52]:
class BinaryClassifier(nn.Module):
  def __init__(self):
    super(BinaryClassifier, self).__init__()
    self.linear = nn.Linear(2, 1)
    self.sigmoid = nn.Sigmoid()
  
  def forward(self, x):
    return self.sigmoid(self.linear(x))

In [53]:
model = BinaryClassifier()

In [55]:
optimizer = optim.SGD(model.parameters(), lr=1)

epochs = 100
for epoch in range(epochs):
  hypothesis = model(x_train)

  print(hypothesis.shape, y_train.shape)
  cost = F.binary_cross_entropy(hypothesis, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 10 == 0:
    prediction = hypothesis >= torch.FloatTensor([0.5])
    correct_prediction = prediction.float() == y_train.float()
    accuracy = correct_prediction.sum().item() / len(correct_prediction)
    print("Epoch: {:4d}/{} Cost: {:6f} Accuracy: {:2.2f}%".format(
        epoch+1, epochs, cost.item(), accuracy * 100
    ))

torch.Size([6, 1]) torch.Size([6, 1])
Epoch:    1/100 Cost: 1.958243 Accuracy: 50.00%
torch.Size([6, 1]) torch.Size([6, 1])
torch.Size([6, 1]) torch.Size([6, 1])
torch.Size([6, 1]) torch.Size([6, 1])
torch.Size([6, 1]) torch.Size([6, 1])
torch.Size([6, 1]) torch.Size([6, 1])
torch.Size([6, 1]) torch.Size([6, 1])
torch.Size([6, 1]) torch.Size([6, 1])
torch.Size([6, 1]) torch.Size([6, 1])
torch.Size([6, 1]) torch.Size([6, 1])
torch.Size([6, 1]) torch.Size([6, 1])
Epoch:   11/100 Cost: 0.673601 Accuracy: 50.00%
torch.Size([6, 1]) torch.Size([6, 1])
torch.Size([6, 1]) torch.Size([6, 1])
torch.Size([6, 1]) torch.Size([6, 1])
torch.Size([6, 1]) torch.Size([6, 1])
torch.Size([6, 1]) torch.Size([6, 1])
torch.Size([6, 1]) torch.Size([6, 1])
torch.Size([6, 1]) torch.Size([6, 1])
torch.Size([6, 1]) torch.Size([6, 1])
torch.Size([6, 1]) torch.Size([6, 1])
torch.Size([6, 1]) torch.Size([6, 1])
Epoch:   21/100 Cost: 0.501478 Accuracy: 66.67%
torch.Size([6, 1]) torch.Size([6, 1])
torch.Size([6, 1]) t