In [1]:
import numpy as np

In [2]:
ary1 = np.array([[1,2,3]])

ary2 = np.array([[1,2,3],
                 [4,5,6]])

In [3]:
np.concatenate((ary1, ary2), axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [4]:
ary1 = np.array([[1,2,3], [4,5,6]])
ary2 = np.array([[7,8,9], [10, 11, 12]])

print(np.stack((ary1, ary2), axis=2))
print("check")
print(np.concatenate((ary1.reshape(2,3,1), ary2.reshape(2,3,1)), axis=2))

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
check
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [5]:
np.vstack((ary1, ary2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
np.hstack((ary1, ary2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [7]:
np.dstack((ary1, ary2))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [8]:
ary1 = np.array([1,2,3])
ary2 = np.array([4,5,6])

In [9]:
np.vstack((ary1, ary2))

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.hstack((ary1, ary2))

array([1, 2, 3, 4, 5, 6])

In [11]:
np.dstack((ary1, ary2))

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [12]:
ary = np.array([1,5,3,4,2])
index = np.where(ary < 3)
print(index)

(array([0, 4]),)


In [13]:
ary[ary < 3]

array([1, 2])

In [14]:
import pandas as pd

In [15]:
pd1 = pd.Series([1,2,3,4], index=['a', 'b', 'c', 'd'])
print(pd1)
print(pd1['a'])

a    1
b    2
c    3
d    4
dtype: int64
1


In [16]:
data = {
    'name':['Jason', 'Paul', 'Kim', 'Tom', 'Lil'],
    'age':[27, 33, 16, 45, 11],
}
pd2 = pd.DataFrame(data=data)

In [17]:
pd2

name  age
0  Jason   27
1   Paul   33
2    Kim   16
3    Tom   45
4    Lil   11

In [18]:
pd2['name']

0    Jason
1     Paul
2      Kim
3      Tom
4      Lil
Name: name, dtype: object

In [19]:
pd2[0:2]

name  age
0  Jason   27
1   Paul   33

In [20]:
pd2[pd2['age'] > 20]

name  age
0  Jason   27
1   Paul   33
3    Tom   45

In [21]:
pd2.loc[0, 'age']

27

In [22]:
pd2['age'] > 20

0     True
1     True
2    False
3     True
4    False
Name: age, dtype: bool

In [23]:
pd2[(pd2['age'] >= 20) & (pd2['age'] < 40)]

name  age
0  Jason   27
1   Paul   33

In [24]:
pd2.sort_values(by=['age', 'name'], ascending=False)

name  age
3    Tom   45
1   Paul   33
0  Jason   27
2    Kim   16
4    Lil   11

In [25]:
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

In [26]:
iris = load_iris()
iris_data, iris_target = iris.data, iris.target

In [27]:
from sklearn.tree import DecisionTreeClassifier

dt_clf = DecisionTreeClassifier()

In [28]:
kfold = KFold(n_splits=5)

In [29]:
for train_index, test_index in kfold.split(iris_data):
  print(train_index)
  print(test_index)

[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 1

In [30]:
from sklearn.model_selection import GridSearchCV

dt_clf = DecisionTreeClassifier()
params = {
    'max_depth':[5,10, 20,],
    'min_samples_leaf':[1,3],
}
grider = GridSearchCV(dt_clf, param_grid = params, scoring="accuracy", cv=3, refit=True)
grider.fit(iris_data, iris_target)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [5, 10, 20], 'min_samples_leaf': [1, 3]},
             scoring='accuracy')

In [31]:
grider.cv_results_

{'mean_fit_time': array([0.00148654, 0.00054447, 0.0005494 , 0.00052238, 0.00054304,
        0.0005153 ]),
 'mean_score_time': array([0.00055591, 0.00029556, 0.00029373, 0.00029397, 0.00028237,
        0.00029031]),
 'mean_test_score': array([0.96      , 0.94666667, 0.96666667, 0.94666667, 0.96      ,
        0.94666667]),
 'param_max_depth': masked_array(data=[5, 5, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_leaf': masked_array(data=[1, 3, 1, 3, 1, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_depth': 5, 'min_samples_leaf': 1},
  {'max_depth': 5, 'min_samples_leaf': 3},
  {'max_depth': 10, 'min_samples_leaf': 1},
  {'max_depth': 10, 'min_samples_leaf': 3},
  {'max_depth': 20, 'min_samples_leaf': 1},
  {'max_depth': 20, 'min_samples_leaf': 3}],
 'rank_test_score': array([2, 4, 1, 4, 2, 4],

In [32]:
grider.best_score_

0.9666666666666667

In [33]:
grider.best_params_

{'max_depth': 10, 'min_samples_leaf': 1}

In [34]:
dt_clf == grider.best_estimator_

False

In [35]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서']
test_items = ['냉장고', 'TV', '믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(test_items)
print(labels)

[1 0 2]


In [36]:
encoder.inverse_transform(labels)

array(['냉장고', 'TV', '믹서'], dtype='<U5')

In [37]:
from sklearn.preprocessing import OneHotEncoder

criterion = encoder.transform(items)
encoder = OneHotEncoder()
encoder.fit(criterion.reshape(-1, 1))
result = encoder.transform(labels.reshape(-1, 1))
print(result)

  (0, 1)	1.0
  (1, 0)	1.0
  (2, 2)	1.0


In [38]:
type(result)

scipy.sparse.csr.csr_matrix

In [39]:
result.toarray()

array([[0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [41]:
import pandas as pd

df = pd.DataFrame({'item':['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '전자레인지', '믹서']})
oneHotEncodered = pd.get_dummies(df)

In [42]:
oneHotEncodered

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        0         0           1         0
8        0         0        1         0           0         0

In [63]:
columns = oneHotEncodered.columns.to_series().apply(lambda x : print(x.title()))

Item_Tv
Item_냉장고
Item_믹서
Item_선풍기
Item_전자레인지
Item_컴퓨터


In [64]:
print(columns)

item_TV       None
item_냉장고      None
item_믹서       None
item_선풍기      None
item_전자레인지    None
item_컴퓨터      None
dtype: object
