In [1]:
import torch
import numpy as np

# Tensor Initializing

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [4]:
x_ones = torch.ones_like(x_data)
print(x_ones)
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.1196, 0.6834],
        [0.1839, 0.5188]])


In [5]:
# shape is represented by tuple
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)
print(rand_tensor.shape)

tensor([[0.7074, 0.0972, 0.5276],
        [0.2660, 0.7317, 0.7499]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])


In [6]:
# Properties of tensor
tensor = torch.rand((3, 4))
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [7]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [8]:
tensor.device

device(type='cuda', index=0)

In [15]:
tensor = torch.arange(25).reshape(5, 5)
tensor

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [16]:
print("First row: ", tensor[0])
print("First col: ", tensor[:, 0])
print("Last  col: ", tensor[:, -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([0, 1, 2, 3, 4])
First col:  tensor([ 0,  5, 10, 15, 20])
Last  col:  tensor([ 4,  9, 14, 19, 24])
tensor([[ 0,  0,  2,  3,  4],
        [ 5,  0,  7,  8,  9],
        [10,  0, 12, 13, 14],
        [15,  0, 17, 18, 19],
        [20,  0, 22, 23, 24]])


In [18]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1.shape)
print(t1)
t2 = torch.cat([tensor, tensor, tensor], dim=0)
print(t2.shape)
print(t2)

torch.Size([5, 15])
tensor([[ 0,  0,  2,  3,  4,  0,  0,  2,  3,  4,  0,  0,  2,  3,  4],
        [ 5,  0,  7,  8,  9,  5,  0,  7,  8,  9,  5,  0,  7,  8,  9],
        [10,  0, 12, 13, 14, 10,  0, 12, 13, 14, 10,  0, 12, 13, 14],
        [15,  0, 17, 18, 19, 15,  0, 17, 18, 19, 15,  0, 17, 18, 19],
        [20,  0, 22, 23, 24, 20,  0, 22, 23, 24, 20,  0, 22, 23, 24]])
torch.Size([15, 5])
tensor([[ 0,  0,  2,  3,  4],
        [ 5,  0,  7,  8,  9],
        [10,  0, 12, 13, 14],
        [15,  0, 17, 18, 19],
        [20,  0, 22, 23, 24],
        [ 0,  0,  2,  3,  4],
        [ 5,  0,  7,  8,  9],
        [10,  0, 12, 13, 14],
        [15,  0, 17, 18, 19],
        [20,  0, 22, 23, 24],
        [ 0,  0,  2,  3,  4],
        [ 5,  0,  7,  8,  9],
        [10,  0, 12, 13, 14],
        [15,  0, 17, 18, 19],
        [20,  0, 22, 23, 24]])


In [23]:
tensor = torch.arange(4).reshape(2, 2)
print(tensor)

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.matmul(tensor, tensor.T)

y1, y2, y3

tensor([[0, 1],
        [2, 3]])


(tensor([[ 1,  3],
         [ 3, 13]]), tensor([[ 1,  3],
         [ 3, 13]]), tensor([[ 1,  3],
         [ 3, 13]]))

In [26]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item)

6


In [31]:
agg = tensor.sum(axis=1)
print(agg)

tensor([1, 5])


In [32]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[0, 1],
        [2, 3]]) 

tensor([[5, 6],
        [7, 8]])


In [33]:
t = torch.arange(5)
print(t)
n = t.numpy()
print(n)

tensor([0, 1, 2, 3, 4])
[0 1 2 3 4]


In [35]:
n[0] = 1000
print(t)
print(n)

tensor([1000,    1,    2,    3,    4])
[1000    1    2    3    4]


In [36]:
t[0] = 2000
print(t)
print(n)

tensor([2000,    1,    2,    3,    4])
[2000    1    2    3    4]


In [38]:
n = np.arange(10)
t = torch.from_numpy(n)
print(n)
print(t)

[0 1 2 3 4 5 6 7 8 9]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
