In [1]:
import torch, torchvision

In [2]:
model = torchvision.models.resnet18(pretrained=True)
data = torch.rand(1,3, 64, 64)
labels = torch.rand(1, 1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


  0%|          | 0.00/44.7M [00:00<?, ?B/s]

In [3]:
prediction = model(data)

In [4]:
x = torch.ones(1, requires_grad=True)
print(x)
y = x + 2
print(y)
print("=============")
y.backward()
print(y)

tensor([1.], requires_grad=True)
tensor([3.], grad_fn=<AddBackward0>)
tensor([3.], grad_fn=<AddBackward0>)


In [5]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 3
out = z.mean()
print(z, out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [6]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [7]:
x = torch.randn(2,1, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
  y = y * 2
print(y)

tensor([[ -76.7357],
        [1269.8506]], grad_fn=<MulBackward0>)


In [8]:
x = torch.tensor([1., 2.], requires_grad=True)
y = x + 1
y

tensor([2., 3.], grad_fn=<AddBackward0>)

In [9]:
y.backward(torch.tensor([1., 500.]))

In [10]:
x.grad

tensor([  1., 500.])

In [11]:
y

tensor([2., 3.], grad_fn=<AddBackward0>)

In [12]:
x = torch.tensor(1., requires_grad=True)
print(x.requires_grad)

with torch.no_grad():
  print(x.requires_grad)
  print((x**2).requires_grad)
print((x**2).requires_grad)

True
True
False
True


In [13]:
x = torch.tensor(1., requires_grad=True)
print(x.requires_grad)
y = x * x
print(y.requires_grad)

True
True


In [19]:
a = torch.tensor(1., requires_grad=True)
b = torch.tensor(1., requires_grad=True)
c = a+b

In [20]:
d = torch.tensor(2., requires_grad=True)
e = c + d

In [21]:
c += 1.

In [27]:
e.backward()
a.grad.item(), b.grad.item()

(6.0, 6.0)

In [28]:
e.backward()
a.grad.item(), b.grad.item()

(7.0, 7.0)

In [29]:
e.backward()
a.grad, b.grad

(tensor(8.), tensor(8.))

#HMM