In [6]:
from nltk import sent_tokenize
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [7]:
text_sample = 'The Matrix is everywhere its all around us, here even in this room. \
You can see it out your window or on your television. \
You feel it when you go to work, or go to church or pay your taxes.'

####a) Lower
####b) deleting special characters, stop word

In [8]:
sentences = sent_tokenize(text=text_sample)

In [9]:
print(type(sentences), len(sentences))
print(sentences)

<class 'list'> 3
['The Matrix is everywhere its all around us, here even in this room.', 'You can see it out your window or on your television.', 'You feel it when you go to work, or go to church or pay your taxes.']


In [10]:
from nltk import word_tokenize

sentence = "The Matrix is everywhere its all around us, here even in this room."
words = word_tokenize(sentence)
print(type(words), len(words))
print(words)

<class 'list'> 15
['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.']


In [11]:
def tokenize_text(text):
  sentences = sent_tokenize(text)
  word_tokens = [word_tokenize(sentence) for sentence in sentences]
  return word_tokens

In [12]:
word_tokens = tokenize_text(text_sample)
print(type(word_tokens), len(word_tokens))
print(word_tokens)

<class 'list'> 3
[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes', '.']]


In [13]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [14]:
print(len(nltk.corpus.stopwords.words('english')))
print(nltk.corpus.stopwords.words('english')[:20])

179
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his']


In [15]:
stopwords = nltk.corpus.stopwords.words('english')
result_tokens = []
for sentence in word_tokens:
  filtered_words = []
  for word in sentence:
    word = word.lower()
    if word not in stopwords:
      filtered_words.append(word)
  result_tokens.append(filtered_words)

In [16]:
print(result_tokens)

[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['see', 'window', 'television', '.'], ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes', '.']]


####c) Stemming (nltk.stem.LancasterStemmer) / Lemmatization (nltk.stem.WordNetLemmatizer)

In [18]:
from nltk.stem import LancasterStemmer

stemmer = LancasterStemmer()

words = [
         'working', 'works', 'worked',
         'amusing', 'amuses', 'amused',
         'happier', 'happiest',
         'fancier', 'fanciest',
]

for word in words:
  print(word, stemmer.stem(word))

working work
works work
worked work
amusing amus
amuses amus
amused amus
happier happy
happiest happiest
fancier fant
fanciest fanciest


In [22]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
lemma = WordNetLemmatizer()
print("==============================")
print(lemma.lemmatize('amusing', 'v'), lemma.lemmatize('amuses', 'v'), lemma.lemmatize('amused', 'v'))
print(lemma.lemmatize('happier', 'a'), lemma.lemmatize('happiest', 'a'))
print(lemma.lemmatize('fancier', 'a'), lemma.lemmatize('fanciest', 'a'))

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
amuse amuse amuse
happy happy
fancy fancy


In [23]:
import numpy as np

dense = np.array([
                  [3, 0, 1],
                  [0, 2, 0],
])

In [25]:
from scipy import sparse

data = dense[dense > 0]

In [35]:
row_pos, col_pos = np.where(dense > 0)
print(data, row_pos, col_pos)

sparse_coo = sparse.coo_matrix((data, (row_pos, col_pos)))

[3 1 2] [0 0 1] [0 2 1]


In [36]:
sparse_coo.toarray()

array([[3, 0, 1],
       [0, 2, 0]])

In [39]:
dense2 = np.array([
                  [0,0,1,0,0,5,],
                  [1,4,0,3,2,5,],
                  [0,6,0,3,0,0,],
                  [2,0,0,0,0,0,],
                  [0,0,0,7,0,8,],
                  [1,0,0,0,0,0,],
])

In [43]:
data2 = np.array([1,5,1,4,3,2,5,6,3,2,7,8,1])
row_pos2, col_pos2 = np.where(dense2 > 0)
sparse_coo = sparse.coo_matrix((data2, (row_pos2, col_pos2)))
print(sparse_coo.toarray())

[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [48]:
row_pos_index = np.array([0,2,7,9,10,12,13])
sparse_csr = sparse.csr_matrix((data2, col_pos2, row_pos_index))
print(sparse_csr.toarray())

[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [50]:
coo = sparse.coo_matrix(dense2)
csr = sparse.csr_matrix(dense2)
print(coo.toarray())
print(csr.toarray())

[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
